// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDeclarationOne(arg1) {
  return window['go']['main']['App']['GenerateDeclarationOne'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig() {
  return window['go']['main']['App']['SaveConfig']();
}
