// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GenerateDeclarationOne():Promise<string>;

export function LoadUserConfig():Promise<main.UserConfig>;

export function SaveUserConfig(arg1:main.UserConfig):Promise<string>;
