// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CalculateTaxForQuarter(arg1, arg2) {
  return window['go']['main']['App']['CalculateTaxForQuarter'](arg1, arg2);
}

export function DeleteData(arg1, arg2) {
  return window['go']['main']['App']['DeleteData'](arg1, arg2);
}

export function GenerateDeclarationOne(arg1, arg2) {
  return window['go']['main']['App']['GenerateDeclarationOne'](arg1, arg2);
}

export function GenerateDeclarationSix(arg1) {
  return window['go']['main']['App']['GenerateDeclarationSix'](arg1);
}

export function LoadAllIncomeData() {
  return window['go']['main']['App']['LoadAllIncomeData']();
}

export function LoadIncomeDataForMonth(arg1, arg2) {
  return window['go']['main']['App']['LoadIncomeDataForMonth'](arg1, arg2);
}

export function LoadSettingsConfig() {
  return window['go']['main']['App']['LoadSettingsConfig']();
}

export function LoadTaxesConfig() {
  return window['go']['main']['App']['LoadTaxesConfig']();
}

export function LoadTaxesConfigLabels() {
  return window['go']['main']['App']['LoadTaxesConfigLabels']();
}

export function LoadThisMonthActions() {
  return window['go']['main']['App']['LoadThisMonthActions']();
}

export function LoadUserConfig() {
  return window['go']['main']['App']['LoadUserConfig']();
}

export function SaveDeclarationToFile(arg1, arg2) {
  return window['go']['main']['App']['SaveDeclarationToFile'](arg1, arg2);
}

export function SaveIncomeForm(arg1) {
  return window['go']['main']['App']['SaveIncomeForm'](arg1);
}

export function SavePaidTaxForQuarter(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePaidTaxForQuarter'](arg1, arg2, arg3);
}

export function SaveSettingsConfig(arg1) {
  return window['go']['main']['App']['SaveSettingsConfig'](arg1);
}

export function SaveTaxesConfig(arg1) {
  return window['go']['main']['App']['SaveTaxesConfig'](arg1);
}

export function SaveUserConfig(arg1) {
  return window['go']['main']['App']['SaveUserConfig'](arg1);
}

export function UpdateForm(arg1) {
  return window['go']['main']['App']['UpdateForm'](arg1);
}
