// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDeclarationOne() {
  return window['go']['main']['App']['GenerateDeclarationOne']();
}

export function GenerateDeclarationSix() {
  return window['go']['main']['App']['GenerateDeclarationSix']();
}

export function GetRemindersText() {
  return window['go']['main']['App']['GetRemindersText']();
}

export function LoadSettingsConfig() {
  return window['go']['main']['App']['LoadSettingsConfig']();
}

export function LoadTaxesConfig() {
  return window['go']['main']['App']['LoadTaxesConfig']();
}

export function LoadUserConfig() {
  return window['go']['main']['App']['LoadUserConfig']();
}

export function SaveSettingsConfig(arg1) {
  return window['go']['main']['App']['SaveSettingsConfig'](arg1);
}

export function SaveUserConfig(arg1) {
  return window['go']['main']['App']['SaveUserConfig'](arg1);
}
