// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateDeclarationOne(arg1:string):Promise<string>;

export function SaveConfig():Promise<string>;
