// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteData(arg1:number,arg2:number):Promise<string>;

export function GenerateDeclarationOne(arg1:number,arg2:number):Promise<string>;

export function GenerateDeclarationSix():Promise<string>;

export function LoadAllIncomeData():Promise<Array<main.IncomeForm>>;

export function LoadSettingsConfig():Promise<main.Settings>;

export function LoadTaxesConfig():Promise<main.TaxesConfig>;

export function LoadTaxesConfigLabels():Promise<Array<string>>;

export function LoadUserConfig():Promise<main.UserConfig>;

export function SaveIncomeForm(arg1:main.IncomeForm):Promise<string>;

export function SaveSettingsConfig(arg1:main.Settings):Promise<string>;

export function SaveUserConfig(arg1:main.UserConfig):Promise<string>;
