name: Wails build

on: push
#  push:
#    tags:
#    # Match any new tag
#      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    strategy:
      # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'bumashtina'
            platform:  'linux/amd64'
            os: 'ubuntu-22.04'
            # TODO
#          - name: 'bumashtina_with_libwebkit2gtk_41'
#            platform:  'linux/amd64'
#            os: 'ubuntu-24.04'
            # TODO
#          - name: 'bumashtina'
#            platform:  'windows/amd64'
#            os: 'windows-latest'
#          - name: 'bumashtina'
#            platform:  'darwin/universal'
#            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: snider/build@v3
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false # TODO
